export const tabbing = [
  {
    cName: 'tab-item ahmad select_tab',
    img: require('../asset/ahmad.JPG'),
    alt: 'ahmad',
    Name: 'Ahmad Abyansyah',
    bio: ' Halo, Perkenalkan nama saya Ahmad Abyansyah,bisa kalian panggil ahmad, saya lahir di kediri, 12 juli 2005.saya merupakan siswa SMK Telkom Malang, di SMK Telkom Malang saya mengambil jurusan "Rekayasa Perangkat Lunak".Sekian Terima kasih.',
    makanan: ' Nasi padang ',
    minuman: ' Jus alpukat ',
    warna: ' biru ',
  },
  {
    cName: 'tab-item ibra',
    img: require('../asset/ibra.JPG'),
    alt: 'ibra',
    Name: 'Favian Ibra Yanuarta',
    bio: ' Halo, Perkenalkan nama saya Favian Ibra Yanuarta,bisa kalian panggil ibra, saya lahir di Blitar, 31 Januari 2006.saya merupakan siswa SMK Telkom Malang, di SMK Telkom Malang saya mengambil jurusan "Rekayasa Perangkat Lunak".Sekian Terima kasih.',
    makanan: ' Nasi goreng ',
    minuman: ' Teh ',
    warna: ' Hitam ',
  },
  {
    cName: 'tab-item arum',
    img: require('../asset/arum.JPG'),
    alt: 'arum',
    Name: 'Dewi Qhoni Sekar Arum',
    bio: ' Halo, Perkenalkan nama saya Dewi Qhoni Sekar Arum,bisa kalian panggil Arum, saya lahir di Malang, 8 Januari 2006.saya merupakan siswa SMK Telkom Malang, di SMK Telkom Malang saya mengambil jurusan "Rekayasa Perangkat Lunak".Sekian Terima kasih.',
    makanan: ' Gado-gado ',
    minuman: ' Milkshake vanilla ',
    warna: ' Toska ',
  },
  {
    cName: 'tab-item destia',
    img: require('../asset/destia.JPG'),
    alt: 'destia',
    Name: 'Destia Wulan Fatmalasari',
    bio: ' Halo, Perkenalkan nama saya Destia Wulan Fatmalasari,bisa kalian panggil destia, saya lahir di Magelang, 10 Januari 2006.saya merupakan siswa SMK Telkom Malang, di SMK Telkom Malang saya mengambil jurusan "Rekayasa Perangkat Lunak".Sekian Terima kasih.',
    makanan: ' Mie ayam ',
    minuman: ' Jus mangga ',
    warna: ' Abu abu ',
  },
];
